[[news]]
date = "2026-06"
content = "Received funding from the National Undergraduate Innovation and Entrepreneurship Training Program."

[[news]]
date = "2026-05"
content = "Joined the Studio for Narrative Spaces at City University of Hong Kong as a Research Assistant."

[[news]]
date = "2026-04"
content = "Children's Motion Capture Wristband authorized as a China Design Patent."

[[news]]
date = "2024"
content = "Won a National Silver Medal in the 14th Challenge Cup, placing in the top 0.21%."
